apiVersion: v1
kind: Service
metadata:
  name: "service-phoenix-todo-{{ .Values.image.tag }}"
  namespace: "phoenix-todo"
spec:
  ports:
    - port: 80
      targetPort: 4000
      protocol: TCP
  type: NodePort
  selector:
    app: "phoenix-todo-{{ .Values.image.tag }}"